# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: twad.club

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
github_url: https://github.com/klugjo/hexo-theme-alpha-dust
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: test@example.com
rss_url: \#

# Footer About Text
footer_about: "The source code is available on Github <a href=\"https://github.com/TwadClub/Twad.Web\">TwadClub</a>."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved  <a href=\"http://twad.club/\">TwadClub</a>"

